### PR TITLE
Fix configure Detection Problems

### PR DESCRIPTION
**Pull request by rdbyk**

### CODE REVIEW

**Comment by Foadsf** [comment]
For those who end up here because of the `scicos` keyword, I asked [Dirk Reusch](https://www.linkedin.com/in/dirk-reusch-15a67913a/) about the `xcos` integration/porting for Balisc, and he recommended trying the 

    test_run("xcos",[],"no_check_error_output")

and see the results.

**Comment by rdbyk** [comment]
Please note, you should try this on the "fix_build_ubuntu_20_04" branch!

**Comment by Foadsf** [comment]
Thanks for the response. For others, [this](https://github.com/rdbyk/balisc/tree/fix_build_ubuntu_20_04) is the right branch.

**Comment by rdbyk** [comment]
Furthermore, find [here](https://github.com/rdbyk/balisc/blob/fix_build_ubuntu_20_04/.github/workflows/c-cpp.yml) the details on how to build the wonderful machine ;-)

**Pull request merged**
